In [9]:
bool_arr=b>10
print(bool_arr)

[ True  True  True  True False False  True  True]


In [12]:
bool_arr=b<10
bool_arr

array([ True, False, False, False, False, False,  True, False])

In [14]:
new_arr=b[b>10]
new_arr

array([13, 16, 11, 15, 17, 19])

In [16]:
new_arr=b[(b>10) & (b<20)]
new_arr

array([13, 16, 11, 15, 17, 19])

In [18]:
c=b
c

array([ 4, 13, 16, 11, 15, 17,  3, 19])

In [20]:
c[:3]=10
c

array([10, 10, 10, 11, 15, 17,  3, 19])

In [23]:
c[c>10]=100
c

array([ 10,  10,  10, 100, 100, 100,   3, 100])

In [26]:
ind=np.where(c==100)
ind

(array([3, 4, 5, 7], dtype=int64),)