In [2]:
import numpy as np
x=np.random.randint(1,10,( 3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print(y)

[[9 6 4]
 [8 7 2]
 [3 8 7]]
[[8 3 6]
 [5 3 5]
 [3 3 1]]


In [4]:
ans=x+y
ans

array([[17,  9, 10],
       [13, 10,  7],
       [ 6, 11,  8]])

In [8]:
x=np.random.randint(1,10,( 3,3))
y=np.random.randint(1,10,(3))
print(x)
print(y)

[[2 2 9]
 [5 6 3]
 [3 1 2]]
[5 5 4]


In [10]:
y=np.transpose(y)
print(y)
ans=x*y
ans

[5 5 4]


array([[10, 10, 36],
       [25, 30, 12],
       [15,  5,  8]])

In [12]:
a=np.random.randint(1,10,(3,2))
b=np.random.randint(1,10,(2,3))
print(a)
print(b)

[[8 8]
 [3 1]
 [7 9]]
[[7 4 3]
 [2 3 1]]


In [16]:
b=np.transpose(b)
print(b)
jay=a*b
print(jay)

[[7 2]
 [4 3]
 [3 1]]
[[56 16]
 [12  3]
 [21  9]]
