In [4]:
import numpy as np

a=[1,2,4]
b=np.array(a)
print(b)
print(type(b))

[1 2 4]
<class 'numpy.ndarray'>


In [6]:
a=[2,4,5,'jay',3,4.3]
b=np.array(a)
print(b)

['2' '4' '5' 'jay' '3' '4.3']


In [9]:
a=[2,3,4,4.5]
b=np.array(a,dtype=int)
print(b)

[2 3 4 4]


In [11]:
a=[2,3,4]
b=np.array(a*2)
print(b)

[2 3 4 2 3 4]


In [14]:
b=np.ones(3,dtype=int)
b

array([1, 1, 1])

In [16]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [19]:
b=np.ones((2,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [23]:
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
b=np.full(3,5)
b

array([5, 5, 5])

In [30]:
b=np.empty(3,dtype=int)
b

array([7340131, 3276849, 3276853])